app.service('jobs', function() {
    this.list = function() {
        return [{
            title:"Full Stack Engineer",
            descriptionOne:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed dignissim congue ante in cursus. Suspendisse faucibus tellus justo, sed placerat elit tempor et. Duis dictum, ligula ac ultricies molestie, nibh dui cursus ligula, sed venenatis urna lacus ac lorem. In in dictum dolor. Sed volutpat nunc ut velit accumsan, non bibendum leo vulputate. Vestibulum a blandit ligula. Proin ultrices pharetra malesuada. Integer nibh justo, cursus nec ante venenatis, consectetur venenatis pu Donec ut dapibus nisl. Etiam vestibulum elementum ipsum, quis feugiat nulla semper sit amet. Proin non justo ut ex sodales interdum in sit amet arcu. Nam egestas arcu eu nisl aliquam cursus. Curabitur et est interdum neque congue congue. Maecenas libero odio, varius eget dolor ac, volutpat faucibus odio. Cras mattis lacus id placerat hendrerit. Nunc placerat, neque id molestie dapibus, justo eros elementum nunc, et lacinia justo purus vitae arcu. Mauris tincidunt nisl ac orci pretium, vel pharetra velit molestie.Vestibulum molestie viverra mi, porttitor ornare urna consequat in. Mauris porttitor nibh at placerat interdum. Suspendisse rhoncus bibendum ornare. Cras tempus in sem in porta. Suspendisse consectetur nibh auctor neque euismod varius. Pellentesque vitae molestie massa. Mauris porttitor tellus sed diam dictum, non ultricies lorem gravida.",
            descriptionTwo:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed dignissim congue ante in cursus. Suspendisse faucibus tellus justo, sed placerat elit tempor et. Duis dictum, ligula ac ultricies molestie, nibh dui cursus ligula, sed venenatis urna lacus ac lorem. In in dictum dolor. Sed volutpat nunc ut velit accumsan, non bibendum leo vulputate. Vestibulum a blandit ligula. Proin ultrices pharetra malesuada. Integer nibh justo, cursus nec ante venenatis, consectetur venenatis pu Donec ut dapibus nisl. Etiam vestibulum elementum ipsum, quis feugiat nulla semper sit amet. Proin non justo ut ex sodales interdum in sit amet arcu. Nam egestas arcu eu nisl aliquam cursus. Curabitur et est interdum neque congue congue. Maecenas libero odio, varius eget dolor ac, volutpat faucibus odio. Cras mattis lacus id placerat hendrerit. Nunc placerat, neque id molestie dapibus, justo eros elementum nunc, et lacinia justo purus vitae arcu. Mauris tincidunt nisl ac orci pretium, vel pharetra velit molestie.Vestibulum molestie viverra mi, porttitor ornare urna consequat in. Mauris porttitor nibh at placerat interdum. Suspendisse rhoncus bibendum ornare. Cras tempus in sem in porta. Suspendisse consectetur nibh auctor neque euismod varius. Pellentesque vitae molestie massa. Mauris porttitor tellus sed diam dictum, non ultricies lorem gravida.",  
            link:"https://www.w3schools.com"
        },
        {
            title:"Web Developer",
            descriptionOne:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed dignissim congue ante in cursus. Suspendisse faucibus tellus justo, sed placerat elit tempor et. Duis dictum, ligula ac ultricies molestie, nibh dui cursus ligula, sed venenatis urna lacus ac lorem. In in dictum dolor. Sed volutpat nunc ut velit accumsan, non bibendum leo vulputate. Vestibulum a blandit ligula. Proin ultrices pharetra malesuada. Integer nibh justo, cursus nec ante venenatis, consectetur venenatis pu Donec ut dapibus nisl. Etiam vestibulum elementum ipsum, quis feugiat nulla semper sit amet. Proin non justo ut ex sodales interdum in sit amet arcu. Nam egestas arcu eu nisl aliquam cursus. Curabitur et est interdum neque congue congue. Maecenas libero odio, varius eget dolor ac, volutpat faucibus odio. Cras mattis lacus id placerat hendrerit. Nunc placerat, neque id molestie dapibus, justo eros elementum nunc, et lacinia justo purus vitae arcu. Mauris tincidunt nisl ac orci pretium, vel pharetra velit molestie.Vestibulum molestie viverra mi, porttitor ornare urna consequat in. Mauris porttitor nibh at placerat interdum. Suspendisse rhoncus bibendum ornare. Cras tempus in sem in porta. Suspendisse consectetur nibh auctor neque euismod varius. Pellentesque vitae molestie massa. Mauris porttitor tellus sed diam dictum, non ultricies lorem gravida.",
            descriptionTwo:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed dignissim congue ante in cursus. Suspendisse faucibus tellus justo, sed placerat elit tempor et. Duis dictum, ligula ac ultricies molestie, nibh dui cursus ligula, sed venenatis urna lacus ac lorem. In in dictum dolor. Sed volutpat nunc ut velit accumsan, non bibendum leo vulputate. Vestibulum a blandit ligula. Proin ultrices pharetra malesuada. Integer nibh justo, cursus nec ante venenatis, consectetur venenatis pu Donec ut dapibus nisl. Etiam vestibulum elementum ipsum, quis feugiat nulla semper sit amet. Proin non justo ut ex sodales interdum in sit amet arcu. Nam egestas arcu eu nisl aliquam cursus. Curabitur et est interdum neque congue congue. Maecenas libero odio, varius eget dolor ac, volutpat faucibus odio. Cras mattis lacus id placerat hendrerit. Nunc placerat, neque id molestie dapibus, justo eros elementum nunc, et lacinia justo purus vitae arcu. Mauris tincidunt nisl ac orci pretium, vel pharetra velit molestie.Vestibulum molestie viverra mi, porttitor ornare urna consequat in. Mauris porttitor nibh at placerat interdum. Suspendisse rhoncus bibendum ornare. Cras tempus in sem in porta. Suspendisse consectetur nibh auctor neque euismod varius. Pellentesque vitae molestie massa. Mauris porttitor tellus sed diam dictum, non ultricies lorem gravida.",
            link:"https://www.w3schools.com"
        },
        {
            title:"Blockchain Engineer",
            descriptionOne:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed dignissim congue ante in cursus. Suspendisse faucibus tellus justo, sed placerat elit tempor et. Duis dictum, ligula ac ultricies molestie, nibh dui cursus ligula, sed venenatis urna lacus ac lorem. In in dictum dolor. Sed volutpat nunc ut velit accumsan, non bibendum leo vulputate. Vestibulum a blandit ligula. Proin ultrices pharetra malesuada. Integer nibh justo, cursus nec ante venenatis, consectetur venenatis pu Donec ut dapibus nisl. Etiam vestibulum elementum ipsum, quis feugiat nulla semper sit amet. Proin non justo ut ex sodales interdum in sit amet arcu. Nam egestas arcu eu nisl aliquam cursus. Curabitur et est interdum neque congue congue. Maecenas libero odio, varius eget dolor ac, volutpat faucibus odio. Cras mattis lacus id placerat hendrerit. Nunc placerat, neque id molestie dapibus, justo eros elementum nunc, et lacinia justo purus vitae arcu. Mauris tincidunt nisl ac orci pretium, vel pharetra velit molestie.Vestibulum molestie viverra mi, porttitor ornare urna consequat in. Mauris porttitor nibh at placerat interdum. Suspendisse rhoncus bibendum ornare. Cras tempus in sem in porta. Suspendisse consectetur nibh auctor neque euismod varius. Pellentesque vitae molestie massa. Mauris porttitor tellus sed diam dictum, non ultricies lorem gravida.",
            descriptionTwo:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed dignissim congue ante in cursus. Suspendisse faucibus tellus justo, sed placerat elit tempor et. Duis dictum, ligula ac ultricies molestie, nibh dui cursus ligula, sed venenatis urna lacus ac lorem. In in dictum dolor. Sed volutpat nunc ut velit accumsan, non bibendum leo vulputate. Vestibulum a blandit ligula. Proin ultrices pharetra malesuada. Integer nibh justo, cursus nec ante venenatis, consectetur venenatis pu Donec ut dapibus nisl. Etiam vestibulum elementum ipsum, quis feugiat nulla semper sit amet. Proin non justo ut ex sodales interdum in sit amet arcu. Nam egestas arcu eu nisl aliquam cursus. Curabitur et est interdum neque congue congue. Maecenas libero odio, varius eget dolor ac, volutpat faucibus odio. Cras mattis lacus id placerat hendrerit. Nunc placerat, neque id molestie dapibus, justo eros elementum nunc, et lacinia justo purus vitae arcu. Mauris tincidunt nisl ac orci pretium, vel pharetra velit molestie.Vestibulum molestie viverra mi, porttitor ornare urna consequat in. Mauris porttitor nibh at placerat interdum. Suspendisse rhoncus bibendum ornare. Cras tempus in sem in porta. Suspendisse consectetur nibh auctor neque euismod varius. Pellentesque vitae molestie massa. Mauris porttitor tellus sed diam dictum, non ultricies lorem gravida.",
            link:"https://www.w3schools.com"
        }
    
    
    
    ]
    }
});